import os
from dotenv import load_dotenv

load_dotenv()

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
    "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "MATICUSDT", "LINKUSDT"
]

TIMEFRAME = "1m"

# 🔥 EXTREME CONFIDENCE ONLY
MIN_SCORE = 8.5

# Cooldown per coin (minutes)
ALERT_COOLDOWN = 10

# ⏰ PREFERRED SCALPING WINDOW (IST)
TRADE_START_HOUR = 17   # 5:30 PM
TRADE_START_MIN = 30

TRADE_END_HOUR = 23     # 11:30 PM
TRADE_END_MIN = 30
